name: my first workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello Sudhamoy, welcome your first github action project"
      - name: Multiline command
        run: |
          node -v
          npm -v
  paraller-job-mac:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_vers
  dependent-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: Echo string
        run: Write Output "Windows String"
      - name: Error steps
        run: doesnotexits
