name: workflow commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::missing semicolon"
      - name: Grouping message
        run: |
          echo "::group::My group Id"
          echo "Inside group"
          echo "::endgroup::"
      - name: masking
        run: echo "::add-mask::Secret String"
      - name: Echo a secret
        run: echo "Secrete String"
